In [2034]:
"Hello"

'Hello'

In [2035]:
import numpy as np

In [2036]:
l = [1, 2, 3, 4, 5, 6]

In [2037]:
l*2

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [2038]:
l

[1, 2, 3, 4, 5, 6]

In [2039]:
type(l)

list

In [2040]:
a1 = np.array(l)

In [2041]:
a1

array([1, 2, 3, 4, 5, 6])

In [2042]:
type(a1)

numpy.ndarray

In [2043]:
a1.ndim

1

In [2044]:
a1.shape

(6,)

In [2045]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [2046]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [2047]:
a.ndim

2

In [2048]:
a.shape

(2, 3)

In [2049]:
b = np.array([[[1, 2, 3,8],
              [4, 5, 6, 9]],
               [[1, 2, 3,8],
              [4, 5, 6, 9]]])

In [2050]:
b

array([[[1, 2, 3, 8],
        [4, 5, 6, 9]],

       [[1, 2, 3, 8],
        [4, 5, 6, 9]]])

In [2051]:
b.ndim

3

In [2052]:
b.shape

(2, 2, 4)

In [2053]:
b.dtype

dtype('int64')

In [2054]:
a = np.ones(5)

In [2055]:
a

array([1., 1., 1., 1., 1.])

In [2056]:
a.ndim

1

In [2057]:
a.dtype

dtype('float64')

In [2058]:
a = np.ones(5,dtype='int')

In [2059]:
a

array([1, 1, 1, 1, 1])

In [2060]:
a = np.ones(5,dtype='str')

In [2061]:
a

array(['1', '1', '1', '1', '1'], dtype='<U1')

In [2062]:
a = np.ones(5,dtype='object')

In [2063]:
a

array([1, 1, 1, 1, 1], dtype=object)

In [2064]:
a = np.ones(5,dtype='int')

In [2065]:
a

array([1, 1, 1, 1, 1])

In [2066]:
a

array([1, 1, 1, 1, 1])

In [2067]:
a = np.ones((3,5))

In [2068]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [2069]:
a.ndim

2

In [2070]:
a.dtype

dtype('float64')

In [2071]:
a = np.ones((2,3,5))

In [2072]:
a

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [2073]:
a.ndim

3

In [2074]:
a = np.ones((2,3,5),dtype='bool')

In [2075]:
a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [2076]:
a.ndim

3

In [2077]:
b = np.zeros(5)

In [2078]:
b

array([0., 0., 0., 0., 0.])

In [2079]:
b.ndim

1

In [2080]:
b.dtype

dtype('float64')

In [2081]:
b = np.zeros((3,4))

In [2082]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [2083]:
b.ndim

2

In [2084]:
np.arange(1)

array([0])

In [2085]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2086]:
m = np.arange(1,10)
m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2087]:
m.ndim

1

In [2088]:
m = np.arange(1,10,2)
m

array([1, 3, 5, 7, 9])

In [2089]:
m = np.arange(1,101)
m

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [2090]:
m.ndim

1

In [2091]:
m.reshape(2,50)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [2092]:
(m.reshape((2,50))).ndim

2

In [2093]:
len(m)

100

In [2094]:
m.reshape((1,100))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [2095]:
m.reshape((5,5,4))

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12],
        [ 13,  14,  15,  16],
        [ 17,  18,  19,  20]],

       [[ 21,  22,  23,  24],
        [ 25,  26,  27,  28],
        [ 29,  30,  31,  32],
        [ 33,  34,  35,  36],
        [ 37,  38,  39,  40]],

       [[ 41,  42,  43,  44],
        [ 45,  46,  47,  48],
        [ 49,  50,  51,  52],
        [ 53,  54,  55,  56],
        [ 57,  58,  59,  60]],

       [[ 61,  62,  63,  64],
        [ 65,  66,  67,  68],
        [ 69,  70,  71,  72],
        [ 73,  74,  75,  76],
        [ 77,  78,  79,  80]],

       [[ 81,  82,  83,  84],
        [ 85,  86,  87,  88],
        [ 89,  90,  91,  92],
        [ 93,  94,  95,  96],
        [ 97,  98,  99, 100]]])

In [2096]:
b = np.arange(1,10).reshape(3,3)

In [2097]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2098]:
b.ndim

2

In [2099]:
b = np.arange(1,10).reshape(1,3,3)

In [2100]:
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [2101]:
np.linspace(1,100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [2102]:
len(np.linspace(1,100))

50

In [2103]:
np.linspace(1,100,num=20,endpoint=False)

array([ 1.  ,  5.95, 10.9 , 15.85, 20.8 , 25.75, 30.7 , 35.65, 40.6 ,
       45.55, 50.5 , 55.45, 60.4 , 65.35, 70.3 , 75.25, 80.2 , 85.15,
       90.1 , 95.05])

In [2104]:
np.linspace(1,100,num=20,endpoint=False, dtype='int')

array([ 1,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [2105]:
np.linspace(1,100,num=20,endpoint=False, dtype='bool')

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [2106]:
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [2107]:
b.ndim

3

In [2108]:
b.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2109]:
b.ravel(order= 'F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [2110]:
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2111]:
b.flatten(order= 'F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [2112]:
a = np.arange(1,16).reshape(3,5)

In [2113]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [2114]:
a = np.arange(1,16).reshape(1,15)

In [2115]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [2116]:
a = np.arange(1,16).reshape(15,1)

In [2117]:
a

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [2118]:
a

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [2119]:
a = np.arange(1,16).reshape(3,5)


In [2120]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [2121]:
np.transpose(a)

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [2122]:
b = np.arange(1,25).reshape(1,3,8)

In [2123]:
b

array([[[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]]])

In [2124]:
b = np.arange(1,25).reshape(2,4,3)

In [2125]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [2126]:
b.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [2127]:
b.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [2128]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(1,10).reshape(3,3)

In [2129]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2130]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2131]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [2132]:
a-b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [2133]:
a1 = np.add(a,b)
a1


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [2134]:
np.subtract(a, b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [2135]:
np.divide(a,b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [2136]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [2137]:
a.min()

np.int64(1)

In [2138]:
a.max()

np.int64(9)

In [2139]:
a.min(axis=0)

array([1, 2, 3])

In [2140]:
a.max(axis=1)

array([3, 6, 9])

In [2141]:
a.max(axis=0)

array([7, 8, 9])

In [2142]:
a.min(axis=1)

array([1, 4, 7])

In [2143]:
np.sum(a)

np.int64(45)

In [2144]:
np.argmin(a)

np.int64(0)

In [2145]:
np.argmax(a)

np.int64(8)

In [2146]:
np.argmin(a,axis=0)

array([0, 0, 0])

In [2147]:
np.argmax(a,axis=1)

array([2, 2, 2])

In [2148]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2149]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [2150]:
np.sum(a,axis=0)

array([12, 15, 18])

In [2151]:
np.trace(a)

np.int64(15)

In [2152]:
np.mean(a)

np.float64(5.0)

In [2153]:
np.median(a)

np.float64(5.0)

In [2154]:
np.std(a)

np.float64(2.581988897471611)

In [2155]:
np.var(a)

np.float64(6.666666666666667)

In [2156]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [2157]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [2158]:
a = np.arange(1,101).reshape(10,10)

In [2159]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [2160]:
a[3]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [2161]:
a[3:6]

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [2162]:
a[3:6 ,3]

array([34, 44, 54])

In [2163]:
a[3:6 ,3:6]

array([[34, 35, 36],
       [44, 45, 46],
       [54, 55, 56]])

In [2164]:
a[3:10:2 ,3:8:2]

array([[34, 36, 38],
       [54, 56, 58],
       [74, 76, 78],
       [94, 96, 98]])

In [2165]:
a[:,3]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [2166]:
a[:3,3]

array([ 4, 14, 24])

In [2167]:
a[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [2168]:
a[:,3:10:2]

array([[  4,   6,   8,  10],
       [ 14,  16,  18,  20],
       [ 24,  26,  28,  30],
       [ 34,  36,  38,  40],
       [ 44,  46,  48,  50],
       [ 54,  56,  58,  60],
       [ 64,  66,  68,  70],
       [ 74,  76,  78,  80],
       [ 84,  86,  88,  90],
       [ 94,  96,  98, 100]])

In [2169]:
t = (1, 2, 3, 4, 5)

In [2170]:
np.array(t)

array([1, 2, 3, 4, 5])

In [2171]:
t = {1, 2, 3, 4, 5}

In [2172]:
np.array(t)

array({1, 2, 3, 4, 5}, dtype=object)

In [2173]:
t = {1, 2, 3, 4, 5}

In [2174]:
d = {"key":"value","Name":"John"}

In [2175]:
np.array(d)

array({'key': 'value', 'Name': 'John'}, dtype=object)

In [2176]:
a = np.array([1, 2, 3, 4])

In [2177]:
a

array([1, 2, 3, 4])

In [2178]:
list(a)

[np.int64(1), np.int64(2), np.int64(3), np.int64(4)]

In [2179]:
tuple(a)

(np.int64(1), np.int64(2), np.int64(3), np.int64(4))

In [2180]:
set(a)

{np.int64(1), np.int64(2), np.int64(3), np.int64(4)}

In [2181]:
str(a)

'[1 2 3 4]'

In [2182]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(1,10).reshape(3,3)

In [2183]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2184]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2185]:
np.dot(a, b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [2186]:
np.multiply(a, b)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

concatanation

In [2187]:
a = np.arange(1,17).reshape(4,4)
b = np.arange(17,33).reshape(4,4)

In [2188]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [2189]:
b

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [2190]:
np.concatenate((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [2191]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [2192]:
np.hstack((a, b))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [2193]:
np.vstack((a ,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [2194]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [2195]:
np.split(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [2196]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [2197]:
np.split(a,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [2198]:
np.split(a,2, axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [2199]:
np.split(a,4, axis=1)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [2200]:
s = np.array([11, 22, 33, 44, 55, 66, 77,88])

In [2201]:
s

array([11, 22, 33, 44, 55, 66, 77, 88])

In [2202]:
np.split(s,[2])

[array([11, 22]), array([33, 44, 55, 66, 77, 88])]

In [2203]:
np.split(s,[3])

[array([11, 22, 33]), array([44, 55, 66, 77, 88])]

In [2204]:
np.split(s,[2])

[array([11, 22]), array([33, 44, 55, 66, 77, 88])]

In [2205]:
np.split(s,[3,7])

[array([11, 22, 33]), array([44, 55, 66, 77]), array([88])]

In [2206]:
np.split(s,[3,4])

[array([11, 22, 33]), array([44]), array([55, 66, 77, 88])]

In [2207]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#from import random *

In [2208]:
np.random.random()

0.50429076180475

In [2209]:
np.random.random((3,5))

array([[0.77690984, 0.9301421 , 0.87597664, 0.7040494 , 0.23516241],
       [0.90190523, 0.91779881, 0.11328332, 0.50367855, 0.39464543],
       [0.32130667, 0.70335498, 0.54223323, 0.32923162, 0.01689841]])

In [2210]:
np.random.random(((2,3,5)))

array([[[0.95983164, 0.14449055, 0.84102223, 0.12180854, 0.64164066],
        [0.0879438 , 0.48442794, 0.51151886, 0.51389286, 0.21745356],
        [0.83839205, 0.59736971, 0.73636564, 0.12125849, 0.55380975]],

       [[0.84371426, 0.6147726 , 0.0692411 , 0.62038741, 0.24517206],
        [0.57576722, 0.92762632, 0.04306461, 0.83836053, 0.50653345],
        [0.57619697, 0.67619769, 0.09378159, 0.47775952, 0.79416054]]])

In [2211]:
np.random.randint(2)

0

In [2212]:
np.random.randint(16)


2

In [2213]:
np.random.randint(15,size=(2, 4))

array([[ 7, 12, 13,  4],
       [ 6, 14, 11, 10]], dtype=int32)

In [2214]:
np.random.randint(15,size=(2, 4,4))

array([[[12, 13,  2,  1],
        [ 4,  4,  6, 10],
        [14,  9,  9,  9],
        [ 2,  5,  7, 12]],

       [[ 6,  9,  2,  4],
        [11,  0, 10,  6],
        [13,  5,  7, 14],
        [ 8,  6,  7,  6]]], dtype=int32)

In [2215]:
np.linspace(1,15)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [2216]:
np.linspace(1,15,25)

array([ 1.        ,  1.58333333,  2.16666667,  2.75      ,  3.33333333,
        3.91666667,  4.5       ,  5.08333333,  5.66666667,  6.25      ,
        6.83333333,  7.41666667,  8.        ,  8.58333333,  9.16666667,
        9.75      , 10.33333333, 10.91666667, 11.5       , 12.08333333,
       12.66666667, 13.25      , 13.83333333, 14.41666667, 15.        ])

In [2217]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [2218]:
np.random.uniform(1,100,250)

array([57.17235924, 43.48087755, 89.81123972, 15.39661376, 74.91957642,
       85.37272301, 78.30995967, 75.20229936, 23.75424333, 66.6739534 ,
       77.44779387, 96.78092693, 22.7201168 , 36.94894151, 52.18903011,
       31.34527045, 83.06693908, 90.30939684, 88.77841961,  6.93451587,
       32.39045605, 29.77771924, 91.32077875, 56.97063182, 85.38752739,
       99.95137474, 74.96612586, 60.1358359 , 87.31664883, 77.36824798,
       94.62609487, 94.18284424, 90.95606551, 45.26005268, 60.3498697 ,
       58.24526035, 32.74022458,  8.43755774, 28.30368095, 37.3254906 ,
       82.40654848, 37.28054953, 79.8559216 , 24.67436839, 74.08234602,
       44.75325377, 36.65354472, 23.58419506, 47.70048097, 40.64190974,
       80.3432825 ,  3.64333273, 91.42475855, 23.63098594, 96.76391596,
       96.62994366,  5.58623048, 18.52524503, 63.36598415,  2.73225798,
        6.53182274, 69.71959165, 47.55352252, 37.73585421, 75.66417651,
       45.18498811, 85.61778465, 32.47500247, 67.57471216, 83.03

In [2219]:
np.random.normal(20,5,100)

array([18.31490126, 24.08507043, 22.1364191 , 22.80651144, 19.09118536,
       27.09618314, 23.33328136, 18.28984436, 20.27539941, 24.71161578,
       15.35320669, 26.64429203, 23.58515694, 29.25282668, 20.97953427,
       20.11385529, 19.02787092, 17.70038368, 26.1672314 , 19.16519594,
       15.15715524, 19.74595513, 19.83396818, 12.3858119 , 18.15247997,
       20.42148544, 18.61204431, 20.07026632, 14.05864345, 20.14575007,
       21.35951369, 15.59434348, 16.03837718, 11.03280538, 13.68902009,
       18.76389746, 25.54735036, 20.16906657, 24.80790275, 16.75472915,
       30.95545478, 23.66071344, 20.17465539, 14.42610672, 26.73171343,
       15.52299195, 19.91696273, 30.99427739, 17.14239324, 19.35495197,
       26.20389362, 20.74787042, 23.93509627, 10.98962478,  6.69371811,
       10.53271346, 24.11517585, 26.93221916, 20.06743845, 13.37903264,
       19.42087065, 10.57597035, 10.74345337, 25.28484435, 35.87194314,
       19.03543033, 23.94598183, 16.3462577 , 18.26541443, 17.33

In [2220]:
len(np.random.uniform(1,100,250))

250

In [2221]:
s = "hello"
s1 ="world"

In [2222]:
s + s1

'helloworld'

In [2223]:
np.char.add(s,s1)

np.str_('helloworld')

In [2224]:
np.char.upper(s)

array('HELLO', dtype='<U5')

In [2225]:
np.char.center(s,20, '*')

array('*******hello********', dtype='<U20')