#1. Import the numpy package under the name np


In [197]:
import numpy as np

#2. Print the numpy version and the configuration

In [203]:
(np.__version__)


'2.1.3'

#3. Create a null vector of size 10

In [199]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#4. Create a vector with values ranging from 10 to 49

In [220]:
np.arange(49).reshape(7,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

#5. Reverse a vector (first element becomes last)


#6. Create a 3x3 matrix with values ranging from 0 to 8

In [246]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [207]:
np.arange(27).reshape((3,3,3))


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#8. Create a 10x10 array with random values and find the minimum and maximum values

In [238]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [239]:
a.min()

np.float64(0.0782141624980982)

In [240]:
a.max()

np.float64(0.8729294085380531)


#9. Create a random vector of size 30 and find the mean value


In [235]:
np.random.randint(30,size=(3,3))

array([[17,  7, 21],
       [27, 29, 25],
       [ 8, 22, 10]], dtype=int32)

In [236]:
a.mean()

np.float64(0.4938720263547489)

In [ ]:
# 10. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [212]:
 a = np.random.random((5,3))
 b = np.random.random((3,2))

In [226]:
a

array([[0.07821416, 0.08158056, 0.7300361 ],
       [0.1062402 , 0.59453074, 0.60049207],
       [0.46743245, 0.35438736, 0.82737986],
       [0.4363596 , 0.70379028, 0.43784878],
       [0.42295777, 0.87292941, 0.69390106]])

In [214]:
b

array([[0.15378841, 0.93148767],
       [0.99940981, 0.05971192],
       [0.60722746, 0.96860044]])

In [215]:
np.dot(a,b)

array([[0.53685881, 0.78484015],
       [0.97515364, 0.71609889],
       [0.92847168, 1.25796921],
       [1.03635577, 0.87258878],
       [1.358816  , 1.11821711]])